import Footer from '@/components/footer/footer'
import Navbar from '@/components/nav/nav'
import type { Metadata } from 'next'
import './../../styles/main.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className="bg-wrapper">
				<Navbar />
				<main className="main-wrapper">
          {children}
				</main>
				<Footer />
			</div>
      </body>
    </html>
  )
}
